# Setup
baseurl: /
url: https://elixirschool.com
permalink: pretty
default_lang: en
exclude_from_localization: []

# Author
author:
  name: Sean Callan
  url: seancallan.com
  email: sean@seancallan.com
  twitter: doomspork
  github: doomspork

plugins:
  - jekyll-assets
  - jekyll-redirect-from
  - jekyll-sitemap
  - kramdown
  - uglifier

# Markdown Config
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Assets
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'Procfile', 'Rakefile', 'vendor']
assets:
  compress:
    css: sass
    js:  uglifier
  digest: true
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts/icomoon

sitemap:
  file: '/sitemap.xml'
  include_posts:
    - '/index.html'
  change_frequency_name: 'change_frequency'
  priority_name: 'priority'

elixir:
  version: 1.5.2

erlang:
  OTP: 20
  erts: 9.1

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      type: "posts"
    values:
      layout: "post"

# Helpers
empty_array: []
